/**
 * Real-world domain knowledge catalog for laptop manufacturers, series,
 * processors (Apple Silicon M1-M5, Intel Core Ultra, AMD Ryzen), and graphics systems.
 */

export const BRAND_CATALOG = {
  Apple: {
    name: 'Apple',
    defaultSeries: 'air',
    series: [
      {
        id: 'air',
        name: 'MacBook Air',
        badge: 'Thin & Light',
        desc: 'Fanless ultra-portable unibody design with all-day battery life and silent operation.',
        formFactor: 'Ultrabook',
        defaultInches: 13.6,
        defaultWeight: 1.24,
        defaultRes: 2560 * 1664,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['m3', 'm2', 'm1', 'm4', 'm5', 'intel_i5', 'intel_i7'],
        defaultChip: 'm2',
        gpuOptions: ['apple_silicon_gpu', 'intel_integrated'],
        defaultGpu: 'apple_silicon_gpu',
        os: ['Mac'],
        marketSeriesMult: 1.0,
      },
      {
        id: 'pro_14',
        name: 'MacBook Pro 13" / 14"',
        badge: 'Pro Performance',
        desc: 'Liquid Retina XDR display, active dual-cooling, studio microphones, and HDMI/SD ports.',
        formFactor: 'Ultrabook',
        defaultInches: 14.2,
        defaultWeight: 1.6,
        defaultRes: 3024 * 1964,
        defaultRam: 18,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['m3_pro', 'm2_pro', 'm1_pro', 'm4_pro', 'm3', 'm2', 'm1', 'intel_i7'],
        defaultChip: 'm3_pro',
        gpuOptions: ['apple_silicon_gpu', 'intel_integrated'],
        defaultGpu: 'apple_silicon_gpu',
        os: ['Mac'],
        marketSeriesMult: 1.12,
      },
      {
        id: 'pro_max',
        name: 'MacBook Pro 16" (Max / High-End)',
        badge: 'Workstation Powerhouse',
        desc: 'Maximum performance architecture with Max-class unified silicon for 3D & 8K ProRes video.',
        formFactor: 'Ultrabook',
        defaultInches: 16.2,
        defaultWeight: 2.15,
        defaultRes: 3456 * 2234,
        defaultRam: 36,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['m3_max', 'm2_max', 'm1_max', 'm4_max', 'm3_pro', 'm2_pro', 'intel_i7'],
        defaultChip: 'm3_max',
        gpuOptions: ['apple_silicon_gpu', 'amd_radeon_pro'],
        defaultGpu: 'apple_silicon_gpu',
        os: ['Mac'],
        marketSeriesMult: 1.25,
      },
      {
        id: 'macbook_12',
        name: 'MacBook (12-inch Legacy)',
        badge: 'Featherweight Legacy',
        desc: '0.92 kg ultra-compact Retina notebook with fanless low-power Intel Core architecture.',
        formFactor: 'Ultrabook',
        defaultInches: 12.0,
        defaultWeight: 0.92,
        defaultRes: 2304 * 1440,
        defaultRam: 8,
        defaultStorage: 256,
        touchSupported: false,
        chipTiers: ['intel_i5', 'intel_other'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Mac'],
        marketSeriesMult: 0.85,
      },
    ],
  },

  Dell: {
    name: 'Dell',
    defaultSeries: 'xps',
    series: [
      {
        id: 'xps',
        name: 'XPS Series (13 / 14 / 15 / 16)',
        badge: 'Flagship Premium',
        desc: 'CNC machined aluminum unibody, carbon-fiber palm rest, and InfinityEdge borderless display.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.45,
        defaultRes: 2560 * 1600,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra5', 'intel_ultra9', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows', 'Linux'],
        marketSeriesMult: 1.15,
      },
      {
        id: 'inspiron',
        name: 'Inspiron Series (Everyday)',
        badge: 'Home & Student',
        desc: 'Accessible everyday workhorse for homework, university, office, and media playback.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.85,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_i5', 'intel_i3', 'intel_i7', 'amd_ryzen5', 'amd_ryzen3'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated', 'nvidia_gtx'],
        defaultGpu: 'intel_integrated',
        os: ['Windows', 'Linux'],
        marketSeriesMult: 0.92,
      },
      {
        id: 'latitude',
        name: 'Latitude Series (Business)',
        badge: 'Enterprise Corporate',
        desc: 'Mil-spec tested corporate laptops with vPro remote hardware security and privacy shutters.',
        formFactor: 'Notebook',
        defaultInches: 14.0,
        defaultWeight: 1.5,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows', 'Linux'],
        marketSeriesMult: 1.05,
      },
      {
        id: 'alienware',
        name: 'Alienware / G-Series (Gaming)',
        badge: 'Dedicated Gaming',
        desc: 'Cryo-tech cooling, mechanical keyboards, high-refresh displays, and dedicated GeForce RTX.',
        formFactor: 'Gaming',
        defaultInches: 16.0,
        defaultWeight: 2.6,
        defaultRes: 2560 * 1600,
        defaultRam: 32,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_ultra9', 'intel_i7', 'amd_ryzen7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30', 'amd_rx'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.25,
      },
      {
        id: 'precision',
        name: 'Precision Mobile Workstation',
        badge: 'ISV Workstation',
        desc: 'Professional CAD, architecture, and video rendering workstation with ECC support.',
        formFactor: 'Workstation',
        defaultInches: 15.6,
        defaultWeight: 2.2,
        defaultRes: 3840 * 2160,
        defaultRam: 32,
        defaultStorage: 1024,
        touchSupported: true,
        chipTiers: ['intel_ultra9', 'intel_i7', 'intel_ultra7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows', 'Linux'],
        marketSeriesMult: 1.28,
      },
    ],
  },

  Lenovo: {
    name: 'Lenovo',
    defaultSeries: 'thinkpad',
    series: [
      {
        id: 'thinkpad',
        name: 'ThinkPad Series (T / X1 / P)',
        badge: 'Legendary Business',
        desc: 'World-renowned ergonomic keyboard, red TrackPoint, spill resistance, and carbon fiber.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.35,
        defaultRes: 1920 * 1200,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'amd_ryzen7', 'intel_i5', 'amd_ryzen5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated', 'amd_integrated', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows', 'Linux'],
        marketSeriesMult: 1.12,
      },
      {
        id: 'yoga',
        name: 'Yoga Series (2-in-1 Convertible)',
        badge: 'Flexible 360° Touch',
        desc: 'Precision geared hinge rotating 360 degrees for tablet, tent, and laptop modes.',
        formFactor: '2 in 1 Convertible',
        defaultInches: 14.0,
        defaultWeight: 1.4,
        defaultRes: 2880 * 1800,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'amd_ryzen7', 'intel_i5'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.08,
      },
      {
        id: 'legion',
        name: 'Legion / LOQ Gaming',
        badge: 'Competitive Gaming',
        desc: 'Coldfront dual-channel thermal systems with dedicated high-TGP Nvidia RTX graphics.',
        formFactor: 'Gaming',
        defaultInches: 16.0,
        defaultWeight: 2.4,
        defaultRes: 2560 * 1600,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_i7', 'amd_ryzen7', 'intel_ultra9', 'amd_ryzen5'],
        defaultChip: 'amd_ryzen7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.18,
      },
      {
        id: 'ideapad',
        name: 'IdeaPad Series',
        badge: 'Student & Everyday',
        desc: 'Well-rounded value laptop designed for university courses, media, and productivity.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.7,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i3', 'amd_ryzen3'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows', 'Chrome OS'],
        marketSeriesMult: 0.90,
      },
    ],
  },

  HP: {
    name: 'HP',
    defaultSeries: 'spectre',
    series: [
      {
        id: 'spectre',
        name: 'Spectre / Envy (Premium Ultrabook)',
        badge: 'Flagship Luxury',
        desc: 'Gem-cut all-metal aesthetic, OLED display options, and Bang & Olufsen tuned audio.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.39,
        defaultRes: 2880 * 1800,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'amd_ryzen7', 'intel_i5'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.12,
      },
      {
        id: 'omen',
        name: 'OMEN / Victus (Gaming)',
        badge: 'Performance Gaming',
        desc: 'OMEN Gaming Hub dynamic fan tuning, high-refresh rates, and discrete RTX graphics.',
        formFactor: 'Gaming',
        defaultInches: 16.1,
        defaultWeight: 2.35,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_i7', 'amd_ryzen7', 'intel_i5', 'amd_ryzen5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.15,
      },
      {
        id: 'pavilion',
        name: 'Pavilion Series',
        badge: 'Mainstream Everyday',
        desc: 'Comfortable family and student notebook with full-sized keyboard and fast charging.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.75,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i3', 'intel_i7'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.90,
      },
      {
        id: 'elitebook',
        name: 'EliteBook / ProBook (Business)',
        badge: 'Corporate Secure',
        desc: 'HP Wolf Security, magnesium alloy chassis, and long lifecycle enterprise battery cells.',
        formFactor: 'Notebook',
        defaultInches: 14.0,
        defaultWeight: 1.4,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'amd_ryzen7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.05,
      },
    ],
  },

  Asus: {
    name: 'Asus',
    defaultSeries: 'rog',
    series: [
      {
        id: 'rog',
        name: 'ROG Series (Zephyrus / Strix)',
        badge: 'Flagship Esports',
        desc: 'Liquid metal cooling, ROG Nebula HDR displays, and max-wattage Nvidia RTX graphics.',
        formFactor: 'Gaming',
        defaultInches: 16.0,
        defaultWeight: 2.2,
        defaultRes: 2560 * 1600,
        defaultRam: 32,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_ultra9', 'amd_ryzen9', 'intel_i7', 'amd_ryzen7'],
        defaultChip: 'amd_ryzen9',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.25,
      },
      {
        id: 'zenbook',
        name: 'ZenBook OLED Series',
        badge: 'Ultra-Slim OLED',
        desc: 'Lumina OLED vivid panels, ErgoLift typing hinge, and all-metal featherweight build.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.25,
        defaultRes: 2880 * 1800,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra5', 'amd_ryzen7', 'intel_i7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.10,
      },
      {
        id: 'tuf',
        name: 'TUF Gaming Series',
        badge: 'Rugged Durability',
        desc: 'Military MIL-STD-810H durability standard with high airflow dual Arc Flow fans.',
        formFactor: 'Gaming',
        defaultInches: 15.6,
        defaultWeight: 2.2,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i7', 'amd_ryzen7', 'intel_i5', 'amd_ryzen5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.10,
      },
      {
        id: 'vivobook',
        name: 'VivoBook Series',
        badge: 'Student & Youth',
        desc: 'Vibrant colorways with 180-degree lay-flat hinges and antimicrobial guard.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.7,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i3'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.90,
      },
    ],
  },

  MSI: {
    name: 'MSI',
    defaultSeries: 'raider',
    series: [
      {
        id: 'raider',
        name: 'Raider / Titan / Vector (Max Gaming)',
        badge: 'Extreme Enthusiast',
        desc: 'Extreme power delivery, mechanical Cherry MX switches, and peak graphics TDP.',
        formFactor: 'Gaming',
        defaultInches: 17.0,
        defaultWeight: 2.8,
        defaultRes: 2560 * 1600,
        defaultRam: 32,
        defaultStorage: 2048,
        touchSupported: false,
        chipTiers: ['intel_ultra9', 'intel_i7', 'amd_ryzen9'],
        defaultChip: 'intel_ultra9',
        gpuOptions: ['nvidia_rtx40'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.30,
      },
      {
        id: 'stealth',
        name: 'Stealth / Thin Series',
        badge: 'Slim Stealth Gaming',
        desc: 'Thin profile magnesium alloy chassis combining executive styling with RTX power.',
        formFactor: 'Gaming',
        defaultInches: 15.6,
        defaultWeight: 1.95,
        defaultRes: 2560 * 1440,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_ultra7', 'intel_i7'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.18,
      },
      {
        id: 'katana',
        name: 'Katana / Sword / Cyborg',
        badge: 'Mainstream Gaming',
        desc: 'Translucent keycaps, specialized heat pipes, and high-value gaming performance.',
        formFactor: 'Gaming',
        defaultInches: 15.6,
        defaultWeight: 2.25,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.08,
      },
      {
        id: 'prestige',
        name: 'Prestige / Modern Series',
        badge: 'Creator & Business',
        desc: 'Ultra-portable sleek design tailored for digital content creators and professionals.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.3,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_ultra7', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.02,
      },
    ],
  },

  Razer: {
    name: 'Razer',
    defaultSeries: 'blade_15',
    series: [
      {
        id: 'blade_15',
        name: 'Razer Blade 14 / 15 / 16',
        badge: 'CNC Aluminum Flagship',
        desc: 'Unibody aircraft-grade aluminum, vapor chamber cooling, and QHD OLED options.',
        formFactor: 'Gaming',
        defaultInches: 15.6,
        defaultWeight: 2.1,
        defaultRes: 2560 * 1440,
        defaultRam: 32,
        defaultStorage: 1024,
        touchSupported: false,
        chipTiers: ['intel_ultra9', 'intel_i7', 'amd_ryzen9'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.30,
      },
      {
        id: 'blade_18',
        name: 'Razer Blade 17 / 18 (Max)',
        badge: 'Desktop Replacement',
        desc: 'Massive 18-inch mini-LED display with desktop-grade thermal headroom and 3 Thunderbolt ports.',
        formFactor: 'Gaming',
        defaultInches: 18.0,
        defaultWeight: 3.1,
        defaultRes: 3840 * 2400,
        defaultRam: 32,
        defaultStorage: 2048,
        touchSupported: false,
        chipTiers: ['intel_ultra9', 'intel_i7'],
        defaultChip: 'intel_ultra9',
        gpuOptions: ['nvidia_rtx40'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.38,
      },
    ],
  },

  Microsoft: {
    name: 'Microsoft',
    defaultSeries: 'surface_laptop',
    series: [
      {
        id: 'surface_laptop',
        name: 'Surface Laptop Series',
        badge: 'Productivity 3:2 Touch',
        desc: '3:2 aspect ratio PixelSense touchscreen with precision glass trackpad and Omnisonic speakers.',
        formFactor: 'Ultrabook',
        defaultInches: 13.5,
        defaultWeight: 1.29,
        defaultRes: 2256 * 1504,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra5', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.10,
      },
      {
        id: 'surface_pro',
        name: 'Surface Pro (2-in-1 Tablet Hybrid)',
        badge: 'Detachable 2-in-1',
        desc: 'Ultra-flexible kickstand with detachable Type Cover keyboard and magnetic stylus.',
        formFactor: '2 in 1 Convertible',
        defaultInches: 13.0,
        defaultWeight: 0.88,
        defaultRes: 2880 * 1920,
        defaultRam: 16,
        defaultStorage: 256,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra5', 'intel_i7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.12,
      },
    ],
  },

  Acer: {
    name: 'Acer',
    defaultSeries: 'predator',
    series: [
      {
        id: 'predator',
        name: 'Predator / Nitro Series',
        badge: 'Esports Gaming',
        desc: 'Dual-fan quad-exhaust cooling with dedicated high-TGP graphics and MUX switch.',
        formFactor: 'Gaming',
        defaultInches: 15.6,
        defaultWeight: 2.3,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i7', 'amd_ryzen7', 'intel_i5', 'amd_ryzen5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['nvidia_rtx40', 'nvidia_rtx30'],
        defaultGpu: 'nvidia_rtx40',
        os: ['Windows'],
        marketSeriesMult: 1.08,
      },
      {
        id: 'swift',
        name: 'Swift Series (Thin & Light)',
        badge: 'Portable All-Metal',
        desc: 'Sub-1.2 kg all-metal chassis with fast-charging battery for on-the-go mobility.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.2,
        defaultRes: 1920 * 1200,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_ultra5', 'intel_i5', 'amd_ryzen5'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.95,
      },
      {
        id: 'aspire',
        name: 'Aspire Series (Everyday)',
        badge: 'Essential Budget',
        desc: 'Everyday budget notebook for web, typing, and standard home media consumption.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.9,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'intel_i3', 'amd_ryzen3', 'intel_other'],
        defaultChip: 'intel_i3',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.88,
      },
      {
        id: 'spin',
        name: 'Spin Series (2-in-1)',
        badge: '360° Touchscreen',
        desc: 'Reversible 360-degree hinge convertible with active stylus support.',
        formFactor: '2 in 1 Convertible',
        defaultInches: 14.0,
        defaultWeight: 1.5,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i7'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.96,
      },
    ],
  },

  Samsung: {
    name: 'Samsung',
    defaultSeries: 'galaxy_book_pro',
    series: [
      {
        id: 'galaxy_book_pro',
        name: 'Galaxy Book Pro / Ultra',
        badge: 'Flagship AMOLED',
        desc: 'Super AMOLED vibrant display, ecosystem integration with Galaxy devices, ultra-slim profile.',
        formFactor: 'Ultrabook',
        defaultInches: 15.6,
        defaultWeight: 1.39,
        defaultRes: 2880 * 1800,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra9', 'intel_i7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx40'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.15,
      },
      {
        id: 'galaxy_book_360',
        name: 'Galaxy Book 360 (2-in-1)',
        badge: 'S-Pen AMOLED Touch',
        desc: '360-degree convertible hinge with bundled S-Pen stylus and AMOLED panel.',
        formFactor: '2 in 1 Convertible',
        defaultInches: 13.3,
        defaultWeight: 1.16,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.10,
      },
      {
        id: 'galaxy_book',
        name: 'Galaxy Book Series (Everyday)',
        badge: 'Everyday Mainstream',
        desc: 'Comfortable all-metal work notebook with Galaxy phone quick-share support.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.6,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'intel_i3'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.95,
      },
    ],
  },

  LG: {
    name: 'LG',
    defaultSeries: 'gram_16',
    series: [
      {
        id: 'gram_16',
        name: 'LG Gram 14 / 16 / 17',
        badge: 'Featherweight Ultrabook',
        desc: 'Sub-1 kg nano-carbon magnesium unibody with massive 80Wh battery.',
        formFactor: 'Ultrabook',
        defaultInches: 16.0,
        defaultWeight: 1.19,
        defaultRes: 2560 * 1600,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_ultra7', 'intel_ultra5', 'intel_i7', 'intel_i5'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.15,
      },
      {
        id: 'gram_2in1',
        name: 'LG Gram 2-in-1',
        badge: 'Lightweight 360° Touch',
        desc: 'Featherweight 360 convertible touchscreen with Wacom AES 2.0 pen support.',
        formFactor: '2 in 1 Convertible',
        defaultInches: 14.0,
        defaultWeight: 1.25,
        defaultRes: 1920 * 1200,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.12,
      },
    ],
  },

  Huawei: {
    name: 'Huawei',
    defaultSeries: 'matebook_x',
    series: [
      {
        id: 'matebook_x',
        name: 'MateBook X Pro',
        badge: 'Premium 3:2 Touch',
        desc: 'Micro-arc oxidation metallic finish with 3.1K Real Color touchscreen display.',
        formFactor: 'Ultrabook',
        defaultInches: 14.2,
        defaultWeight: 1.26,
        defaultRes: 3120 * 2080,
        defaultRam: 16,
        defaultStorage: 1024,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_ultra9', 'intel_i7'],
        defaultChip: 'intel_ultra7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.12,
      },
      {
        id: 'matebook_d',
        name: 'MateBook D Series',
        badge: 'Mainstream Student',
        desc: 'Sleek metal body with FullView display and fingerprint power button.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.68,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i3'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.90,
      },
    ],
  },

  Xiaomi: {
    name: 'Xiaomi',
    defaultSeries: 'book_pro',
    series: [
      {
        id: 'book_pro',
        name: 'Xiaomi Book Pro (OLED)',
        badge: 'High-Res OLED Creator',
        desc: 'E4 OLED touch display with CNC unibody and high-density fast charging.',
        formFactor: 'Ultrabook',
        defaultInches: 14.0,
        defaultWeight: 1.4,
        defaultRes: 2880 * 1800,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_ultra7', 'intel_i7', 'amd_ryzen7'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated', 'nvidia_rtx30'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.05,
      },
      {
        id: 'redmibook',
        name: 'RedmiBook Series',
        badge: 'High-Value Mainstream',
        desc: 'Cost-effective high-performance notebook with full port connectivity.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.78,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'amd_ryzen5', 'intel_i7'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated', 'amd_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.90,
      },
    ],
  },

  Google: {
    name: 'Google',
    defaultSeries: 'pixelbook',
    series: [
      {
        id: 'pixelbook',
        name: 'Pixelbook / Pixelbook Go',
        badge: 'Flagship Chrome OS',
        desc: 'Hush Keys quiet typing, 3:2 Molecular touch display, and lightweight magnesium build.',
        formFactor: 'Ultrabook',
        defaultInches: 13.3,
        defaultWeight: 1.06,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 128,
        touchSupported: true,
        chipTiers: ['intel_i5', 'intel_i7', 'intel_other'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Chrome OS'],
        marketSeriesMult: 1.05,
      },
    ],
  },

  Toshiba: {
    name: 'Toshiba',
    defaultSeries: 'portege',
    series: [
      {
        id: 'portege',
        name: 'Portégé / Dynabook (Business)',
        badge: 'Ultra-Lightweight Corporate',
        desc: 'Japanese engineered honeycomb magnesium chassis with military drop testing.',
        formFactor: 'Ultrabook',
        defaultInches: 13.3,
        defaultWeight: 1.05,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: true,
        chipTiers: ['intel_i7', 'intel_i5'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.0,
      },
      {
        id: 'tecra',
        name: 'Tecra Series (Workhorse)',
        badge: 'Enterprise Standard',
        desc: 'Standard enterprise business laptop with dedicated number pad and docking support.',
        formFactor: 'Notebook',
        defaultInches: 15.6,
        defaultWeight: 1.75,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i5', 'intel_i7'],
        defaultChip: 'intel_i5',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.92,
      },
    ],
  },

  Fujitsu: {
    name: 'Fujitsu',
    defaultSeries: 'lifebook',
    series: [
      {
        id: 'lifebook',
        name: 'Lifebook Series (Made in Japan)',
        badge: 'Sub-900g Ultrabook',
        desc: 'Ultra-featherweight Japanese design with PalmSecure biometric vein scanner.',
        formFactor: 'Ultrabook',
        defaultInches: 13.3,
        defaultWeight: 0.89,
        defaultRes: 1920 * 1080,
        defaultRam: 16,
        defaultStorage: 512,
        touchSupported: false,
        chipTiers: ['intel_i7', 'intel_i5'],
        defaultChip: 'intel_i7',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 1.05,
      },
    ],
  },

  Chuwi: {
    name: 'Chuwi',
    defaultSeries: 'herobook',
    series: [
      {
        id: 'herobook',
        name: 'HeroBook / FreeBook',
        badge: 'Ultra-Budget Compact',
        desc: 'Low-power accessible compact notebook for typing, web browsing, and simple office tasks.',
        formFactor: 'Notebook',
        defaultInches: 14.1,
        defaultWeight: 1.39,
        defaultRes: 1920 * 1080,
        defaultRam: 8,
        defaultStorage: 256,
        touchSupported: false,
        chipTiers: ['intel_other', 'intel_i3'],
        defaultChip: 'intel_other',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.80,
      },
    ],
  },

  Mediacom: {
    name: 'Mediacom',
    defaultSeries: 'smartbook',
    series: [
      {
        id: 'smartbook',
        name: 'SmartBook Series',
        badge: 'Basic Entry',
        desc: 'Entry-level budget portable laptop for schoolwork and essential browsing.',
        formFactor: 'Notebook',
        defaultInches: 14.0,
        defaultWeight: 1.45,
        defaultRes: 1366 * 768,
        defaultRam: 4,
        defaultStorage: 128,
        touchSupported: false,
        chipTiers: ['intel_other'],
        defaultChip: 'intel_other',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.75,
      },
    ],
  },

  Vero: {
    name: 'Vero',
    defaultSeries: 'k_series',
    series: [
      {
        id: 'k_series',
        name: 'Vero K-Series Notebook',
        badge: 'Essential Compact',
        desc: 'Lightweight entry notebook for office document processing and streaming.',
        formFactor: 'Notebook',
        defaultInches: 14.0,
        defaultWeight: 1.4,
        defaultRes: 1920 * 1080,
        defaultRam: 4,
        defaultStorage: 128,
        touchSupported: false,
        chipTiers: ['intel_other'],
        defaultChip: 'intel_other',
        gpuOptions: ['intel_integrated'],
        defaultGpu: 'intel_integrated',
        os: ['Windows'],
        marketSeriesMult: 0.75,
      },
    ],
  },
};

/**
 * Processor Catalog mapping real-world chips to ML model categories & market valuation weights.
 */
export const PROCESSOR_CATALOG = {
  // Apple Silicon (M1 to M5)
  m5: {
    label: 'Apple M5 (Next-Gen Flagship)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.6,
    marketWeight: 0.68,
    desc: 'Cutting-edge next-generation silicon with dedicated neural accelerators.',
  },
  m4_max: {
    label: 'Apple M4 Max (Extreme Workstation)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.5,
    marketWeight: 0.64,
    desc: 'High memory bandwidth, 16-core CPU, and 40-core GPU for extreme rendering.',
  },
  m4_pro: {
    label: 'Apple M4 Pro (Pro Studio)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.4,
    marketWeight: 0.58,
    desc: 'Enhanced pro silicon with thunderbolt 5 support and dynamic caching.',
  },
  m4: {
    label: 'Apple M4 (Latest Generation)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.3,
    marketWeight: 0.54,
    desc: 'Unmatched single-core performance and AI neural acceleration.',
  },
  m3_max: {
    label: 'Apple M3 Max (3nm Powerhouse)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.4,
    marketWeight: 0.60,
    desc: 'Hardware-accelerated ray tracing, mesh shading, and 128GB unified RAM headroom.',
  },
  m3_pro: {
    label: 'Apple M3 Pro (Studio Pro)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.2,
    marketWeight: 0.54,
    desc: 'Dynamic caching GPU architecture with 18-core GPU and 150GB/s bandwidth.',
  },
  m3: {
    label: 'Apple M3 (3nm Generation)',
    family: 'Apple',
    mlCpuBrand: 'Intel i5',
    speedGhz: 3.0,
    marketWeight: 0.50,
    desc: 'Modern 3-nanometer silicon with hardware AV1 decode engine.',
  },
  m2_max: {
    label: 'Apple M2 Max (Heavy Duty)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.3,
    marketWeight: 0.56,
    desc: '38-core GPU with 400 GB/s unified memory bandwidth.',
  },
  m2_pro: {
    label: 'Apple M2 Pro (Pro Creator)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.1,
    marketWeight: 0.50,
    desc: '12-core CPU and 19-core GPU for Xcode and Premiere rendering.',
  },
  m2: {
    label: 'Apple M2 (Popular Standard)',
    family: 'Apple',
    mlCpuBrand: 'Intel i5',
    speedGhz: 2.8,
    marketWeight: 0.46,
    desc: 'Proactive power efficiency with ProRes video encode/decode acceleration.',
  },
  m1_max: {
    label: 'Apple M1 Max (Revolutionary Workstation)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.2,
    marketWeight: 0.50,
    desc: 'Dual ProRes encode engines with 32-core GPU and 400 GB/s bandwidth.',
  },
  m1_pro: {
    label: 'Apple M1 Pro (Pro Pioneer)',
    family: 'Apple',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.0,
    marketWeight: 0.45,
    desc: 'Breakthrough 10-core pro silicon with 200 GB/s unified memory.',
  },
  m1: {
    label: 'Apple M1 (Value Pioneer)',
    family: 'Apple',
    mlCpuBrand: 'Intel i5',
    speedGhz: 2.5,
    marketWeight: 0.40,
    desc: 'First-generation Apple Silicon, outstanding battery & silent fanless operation.',
  },
  intel_i7: {
    label: 'Intel Core i7 (Retina / PC)',
    family: 'PC',
    mlCpuBrand: 'Intel i7',
    speedGhz: 2.6,
    marketWeight: 0.45,
    desc: 'High-performance multi-threaded computing for demanding applications.',
  },
  intel_i5: {
    label: 'Intel Core i5 (Everyday / Retina)',
    family: 'PC',
    mlCpuBrand: 'Intel i5',
    speedGhz: 2.3,
    marketWeight: 0.38,
    desc: 'Mainstream quad/hexa core processor with solid multitasking.',
  },

  // Modern PC Processors
  intel_ultra9: {
    label: 'Intel Core Ultra 9 / Core i9',
    family: 'PC',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.4,
    marketWeight: 0.58,
    desc: 'Flagship enthusiast tier with onboard NPU and maximum boost clock.',
  },
  intel_ultra7: {
    label: 'Intel Core Ultra 7',
    family: 'PC',
    mlCpuBrand: 'Intel i7',
    speedGhz: 3.0,
    marketWeight: 0.50,
    desc: 'High-performance hybrid architecture for creative professionals and gamers.',
  },
  intel_ultra5: {
    label: 'Intel Core Ultra 5',
    family: 'PC',
    mlCpuBrand: 'Intel i5',
    speedGhz: 2.6,
    marketWeight: 0.44,
    desc: 'Balanced productivity and power efficiency with Intel AI Boost.',
  },
  intel_i3: {
    label: 'Intel Core i3',
    family: 'PC',
    mlCpuBrand: 'Intel i3',
    speedGhz: 2.0,
    marketWeight: 0.32,
    desc: 'Entry-level dual/quad core for web browsing, streaming, and documents.',
  },
  amd_ryzen9: {
    label: 'AMD Ryzen 9 (Zen 4 / Zen 5)',
    family: 'PC',
    mlCpuBrand: 'AMD',
    speedGhz: 3.3,
    marketWeight: 0.56,
    desc: 'Top-tier 16-core mobile processor with Radeon 780M/890M graphics.',
  },
  amd_ryzen7: {
    label: 'AMD Ryzen 7',
    family: 'PC',
    mlCpuBrand: 'AMD',
    speedGhz: 2.9,
    marketWeight: 0.48,
    desc: '8-core high efficiency processor with impressive multi-thread power.',
  },
  amd_ryzen5: {
    label: 'AMD Ryzen 5',
    family: 'PC',
    mlCpuBrand: 'AMD',
    speedGhz: 2.6,
    marketWeight: 0.40,
    desc: 'Solid mainstream 6-core performer for daily multitasking.',
  },
  amd_ryzen3: {
    label: 'AMD Ryzen 3',
    family: 'PC',
    mlCpuBrand: 'AMD',
    speedGhz: 2.2,
    marketWeight: 0.30,
    desc: 'Budget-friendly quad-core computing.',
  },
  intel_other: {
    label: 'Intel Celeron / Pentium / Basic',
    family: 'PC',
    mlCpuBrand: 'Intel Other',
    speedGhz: 1.6,
    marketWeight: 0.22,
    desc: 'Low-power entry computing processor for basic tasks.',
  },
};

/**
 * Graphics Systems Catalog
 */
export const GRAPHICS_CATALOG = {
  apple_silicon_gpu: {
    label: 'Apple Silicon Unified GPU',
    isDedicated: false,
    mlGpuBrand: 'Intel',
    desc: 'Direct unified high-speed memory access on the SoC (8 to 40 cores) with Metal acceleration.',
  },
  intel_integrated: {
    label: 'Intel Iris Xe / Arc / UHD Graphics (Integrated)',
    isDedicated: false,
    mlGpuBrand: 'Intel',
    desc: 'Shared processor memory. Low power consumption and cool, quiet operation.',
  },
  amd_integrated: {
    label: 'AMD Radeon 600M / 700M / 800M (Integrated)',
    isDedicated: false,
    mlGpuBrand: 'AMD',
    desc: 'RDNA onboard graphics offering capable 1080p gaming and efficient media decode.',
  },
  nvidia_rtx40: {
    label: 'Nvidia GeForce RTX 40-Series (Dedicated)',
    isDedicated: true,
    mlGpuBrand: 'Nvidia',
    desc: 'DLSS 3 frame generation, dedicated Ray Tracing Cores, and GDDR6 VRAM.',
  },
  nvidia_rtx30: {
    label: 'Nvidia GeForce RTX 30-Series (Dedicated)',
    isDedicated: true,
    mlGpuBrand: 'Nvidia',
    desc: 'Dedicated Ray Tracing and AI Tensor cores for demanding titles and 3D modeling.',
  },
  nvidia_gtx: {
    label: 'Nvidia GeForce GTX / MX Series (Dedicated)',
    isDedicated: true,
    mlGpuBrand: 'Nvidia',
    desc: 'Entry-level dedicated VRAM for lightweight 3D tasks and esports.',
  },
  amd_rx: {
    label: 'AMD Radeon Dedicated RX-Series (Dedicated)',
    isDedicated: true,
    mlGpuBrand: 'AMD',
    desc: 'Dedicated discrete graphics for high frame-rate rendering and creative applications.',
  },
  amd_radeon_pro: {
    label: 'AMD Radeon Pro Dedicated (Intel MacBook)',
    isDedicated: true,
    mlGpuBrand: 'AMD',
    desc: 'Dedicated workstation graphics found on 15" and 16" Intel MacBooks.',
  },
};

/**
 * Release Era / Market Depreciation Factors (Used Market Reality)
 */
export const RELEASE_ERAS = [
  {
    id: 'current',
    label: '2024 – 2026 (Current Generation)',
    factor: 1.15,
    desc: 'Current generation with minimal hardware depreciation and fresh battery health.',
  },
  {
    id: 'recent',
    label: '2022 – 2023 (1–2 Years Old)',
    factor: 1.0,
    desc: 'Standard benchmark used market pricing with minor depreciation.',
  },
  {
    id: 'mid',
    label: '2020 – 2021 (3–4 Years Old)',
    factor: 0.82,
    desc: 'Moderate depreciation cycle with typical battery cycle wear.',
  },
  {
    id: 'legacy',
    label: '2018 – 2019 (Legacy / Pre-2020)',
    factor: 0.65,
    desc: 'Substantial depreciation; older generation architecture and battery age.',
  },
];
